[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "tempit-manager"
version = "0.1.0"
description = "Manage and jump into temporary working directories"
readme = "README.md"
requires-python = ">=3.10,<3.14"
authors = [{ name = "Idir Oura", email = "idir.oura@protonmail.com" }]
dependencies = [
    "humanize",
    "tabulate",
    "termcolor"
]

[project.scripts]
tempit = "tempit.cli:main"

[tool.poetry]
packages = [{ include = "tempit" }]
include = [
  { path = "tempit/shell/init.sh" }
]
